# Generated by Django 5.0.6 on 2024-06-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
