# Generated by Django 5.0.6 on 2024-06-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exchangerate_base_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(max_length=3),
        ),
    ]
