# Generated by Django 5.0.6 on 2024-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cadexchangerate_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AlterField(
            model_name='cadexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eurexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usdexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
